### PR TITLE
[bugfix] properly include all makiwich icons

### LINKED ISSUE #3: 3 symbols return the pin without the corresponding icon
For the following symbols,

* dog-park
* grocery
* karaoke

when I do below operation

```
var makiwich = require('@mapbox/makiwich');
var mapnik = require('mapnik');

makiwich({
    tint: '#454545',
    symbol: 'dog-park', // Valid Maki v2.1.0 icon
    size: 'l' // `s` or `l`
}, (err, svg) => {
    if (err) throw err;

    // Use mapnik to convert the SVG to a PNG and save it
    var s = new mapnik.Image.fromSVGBytesSync(new Buffer(svg), { scale: 2 });
    s.premultiplySync();
    s.saveSync(`dog-park.png`);
});
```
It does not return the pin with icon but only the pin, e.g
dog-park

Are you able to reproduce?

**Environment**:

* OS: `Ubuntu 16.04` 64 bits
* Node version: LTS `6.12.0`,
* npm package @mapbox/makiwich: version `0.0.7`
* npm package mapnik: version `3.6.2`

### PR DESCRIPTION
**Pull request by riastrad**
Fixes #3

## Context

Previously, passing in valid maki icon names would result in blank marker pins for some symbols. This was due to the naive assumption that all of the maki svgs provided by [`@mapbox/maki`](https://github.com/mapbox/maki) are standardized. They were not standard in previous versions and as a result any icon that hit the following line would set `undefined` as the path value for the maki icon base layer:
https://github.com/mapbox/makiwich/blob/b80cb683be19d24685f256ee42f00cc9c3e65fa2/index.js#L26

Fortunately, @willymaps noticed this inconsistency upstream and standardized the maki SVGs in https://github.com/mapbox/maki/issues/541.

### Summary of Changes

- Fixes some minor trailing whitespace lint issues in `index.js`
- Upgrades to `@mapbox/maki@7.0.0`
- Adds logic to scale down maki for smaller icons, now that maki only provides one size
- Updates test fixtures for existing maki icon tests
- Adds new test fixtures for new maki icons

---
**appendix:**

Here's the complete list of icons that were broken prior to this PR:
- `communication-tower`
- `confectionery`
- `convenience`
- `dog-park`
- `grocery`
- `karaoke`
- `restaurant-noodle`
- `restaurant-pizza`
- `restaurant-seafood`
- `slipway`

Here's the list of new icons that this PR adds support for:
- `lighthouse-JP`
- `monument-JP`
- `observation-tower`
- `racetrack-boat`
- `racetrack-cycling`
- `racetrack-horse`
- `racetrack`
- `restaurant-bbq`
- `restaurant-sushi`
- `road-accident`

cc/ @mapbox/map-design-team

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -19,11 +20,24 @@ function generateMarker (options, callback) {
...
+
+        if (!assets.parsedSVGs[symbolName]) {
+            return callback(errcode(`Symbol ${options.symbol} not valid`, 'EINVALID'));
+        }
+
+        // because maki@7.0.0 removed small SVGs, we need to update our small-marker SVG
+        // to reduce the size of the maki icon it renders by the appropriate ratio
+        if (isMaki(options.symbol) && size === 's') {
+            basePaths[3]['$'].transform += ' scale(0.733, 0.733)';
+        }
```
Comment (tristen) [inline index.js:37]: oof this is slightly annoying. Curious what size usage is like and whether that should be deprecated in a future version of the API or changed to a `scale` parameter for dynamic sizing.

File: index.js [hunk 2]
```diff
@@ -5,6 +5,7 @@ var constants = require('./lib/constants');
 var assets = require('./lib/loadAssets');
 var errcode = require('err-code');
 var allColors = [];
+var numericSizes = {'s': 11, 'l': 15};
```
Comment (tristen) [inline index.js:8]: Not sure I understand why this needs to be accounted for if Maki@7 excludes these size variations?

Comment (riastrad) [reply index.js:8]: Great question! We still use these sizes when generating the alphabet & numeric SVG symbols to place on top of marker. So this is sticking around purely to account for that variation.

File: index.js (hunk 1 above)
Comment (riastrad) [reply index.js:37]: Ugh, yeah. I briefly thought about this and then banished the thought because this PR was supposed to just be a quick bug fix. 

I know anecdotally that the downstream dependencies definitely do make frequent use of the the size param, but I'd probably want dig for more data about it before running with a change to the API. 

I don't think we'd ever be able to remove the sizing options entirely, but exposing `scale` instead of a hardcoded size value is very appealing and could be worth a future update to the API.

**Review by shabnomnom — APPROVED** [review]
Looks good. Thanks for implementing this.
